import Head from 'next/head'
import Image from 'next/image'
import axios from "axios"
import Feature from '../Components/Feature'
import PizzaList from '../Components/PizzaList'
import Testimonials from '../Components/Testimonials'
import styles from '../styles/Home.module.css'
import { NEXT_URL } from '../url'



export default function Home({product}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Feature />
      <Testimonials />
      <PizzaList product={product}/>

     
    </div>
  )
}

export async function  getServerSideProps () {
  const res = await axios.get(NEXT_URL + "/api/products")
  // console.log(res.data);
  return {
    props: {
      product:res.data
    },
  }
}

//"http://localhost:3000/api/products"